#!/bin/bash -e

if [ -z $1 ]; then 
	echo "Usage:"
	echo "build_image </path/to/app.jar> <image_name:version>"; 
	exit 1
fi


if [ ! -f $1 ]; then
    echo "File $1 not found!"
    exit 1
fi

if [ ! -z $2 ]; then
    echo "Name or version of the image not present!"
    echo "Usage:"
    echo "build_image </path/to/app.jar> <image_name:version>"; 
    exit 1
fi

APP_PATH=`readlink -f $1`
IMAGE_NAME=$2

SANDBOX="/tmp/mf2c/container"
rm -rf ${SANDBOX}
mkdir -p ${SANDBOX}

INIT_DIR=`pwd`
RUNTIME_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cp ${RUNTIME_DIR}/Dockerfile_app ${SANDBOX}/Dockerfile

mkdir -p ${SANDBOX}/arrel/root

cp ${APP_PATH} ${SANDBOX}/arrel/root/app.jar

cd ${SANDBOX}
ls
docker build -t ${IMAGE_NAME} .
rm -rf ${SANDBOX}

cd ${INIT_DIR}
