#!/bin/bash -e

if [ -z $1 ]; then 
	echo "Usage:"
	echo "build_image </path/to/app.jar>"; 
	exit 1
fi


if [ ! -f $1 ]; then
    echo "File $1 not found!"
    exit 1
fi

APP_PATH=`readlink -f $1`

SANDBOX="/tmp/mf2c/container"
rm -rf ${SANDBOX}
mkdir -p ${SANDBOX}

INIT_DIR=`pwd`
RUNTIME_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cp ${RUNTIME_DIR}/Dockerfile_app ${SANDBOX}/Dockerfile

mkdir -p ${SANDBOX}/arrel/root

cp ${APP_PATH} ${SANDBOX}/arrel/root/app.jar

cd ${SANDBOX}
ls
docker build -t compss-test:1.0 .
rm -rf ${SANDBOX}

cd ${INIT_DIR}
