#!/bin/bash -e


SANDBOX="/tmp/mf2c/container"
rm -rf ${SANDBOX}
mkdir -p ${SANDBOX}

INIT_DIR=`pwd`
RUNTIME_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cp ${RUNTIME_DIR}/Dockerfile_runtime ${SANDBOX}/Dockerfile

cd "${RUNTIME_DIR}/../../../compss"
RUNTIME_DIR=`pwd`

mvn -DskipTests clean install

mkdir -p ${SANDBOX}/arrel/opt/COMPSs/Runtime/adaptors/mf2c/master/
mkdir -p ${SANDBOX}/arrel/opt/COMPSs/Runtime/configuration

cp ${RUNTIME_DIR}/runtime/agent/target/compss-agent-2.2.rc1803.jar ${SANDBOX}/arrel/opt/COMPSs/Runtime/compss-agent.jar
cp ${RUNTIME_DIR}/runtime/adaptors/mf2c/master/compss-adaptors-mf2c-master.jar ${SANDBOX}/arrel/opt/COMPSs/Runtime/adaptors/mf2c/master/compss-adaptors-mf2c-master.jar
cp ${RUNTIME_DIR}/runtime/config/log/COMPSsMaster-log4j.debug ${SANDBOX}/arrel/opt/COMPSs/Runtime/configuration/COMPSsMaster-log4j.debug
cp ${RUNTIME_DIR}/runtime/config/log/COMPSsMaster-log4j.off ${SANDBOX}/arrel/opt/COMPSs/Runtime/configuration/COMPSsMaster-log4j.off

cd ${SANDBOX}
ls
docker build -t compss-agent:latest .
rm -rf ${SANDBOX}

cd ${INIT_DIR}
