FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y \
        csh \
        openjdk-8-jdk  \
        openssh-client \
        openssh-server \
        ssh \
        vim && \
    mkdir /var/run/sshd && \
    echo 'root:screencast' | chpasswd && \
    sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
    echo "export VISIBLE=now" >> /etc/profile && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    yes yes | ssh-keygen -f /root/.ssh/id_rsa -t rsa -N '' > /dev/null && \
    cat /root/.ssh/id_rsa.pub > /root/.ssh/authorized_keys

COPY ["arrel", "/"]
ENV MF2C_HOST=localhost DEBUG=off REPORT_ADDRESS="null"

CMD /opt/COMPSs/launchers/launch.sh -h ${MF2C_HOST} -d ${DEBUG} -ra ${REPORT_ADDRESS}

